# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\delete_user_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteUserForm(object):
    def setupUi(self, DeleteUserForm):
        DeleteUserForm.setObjectName("DeleteUserForm")
        DeleteUserForm.resize(400, 301)
        DeleteUserForm.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget = QtWidgets.QWidget(DeleteUserForm)
        self.widget.setGeometry(QtCore.QRect(70, 80, 300, 100))
        self.widget.setMinimumSize(QtCore.QSize(300, 100))
        self.widget.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"")
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(9, 71, 282, 21))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete_button = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_button.setFont(font)
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_button.setStyleSheet("color: red;\n"
"")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.cencel_button = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cencel_button.setFont(font)
        self.cencel_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cencel_button.setObjectName("cencel_button")
        self.horizontalLayout.addWidget(self.cencel_button)
        self.widget2 = QtWidgets.QWidget(self.widget)
        self.widget2.setGeometry(QtCore.QRect(9, 9, 281, 56))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.quastion = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.quastion.setFont(font)
        self.quastion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.quastion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quastion.setScaledContents(False)
        self.quastion.setAlignment(QtCore.Qt.AlignCenter)
        self.quastion.setObjectName("quastion")
        self.verticalLayout.addWidget(self.quastion)
        self.lineEdit = QtWidgets.QLineEdit(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setMaxLength(8)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.line = QtWidgets.QFrame(self.widget2)
        self.line.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"padding:0;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)

        self.retranslateUi(DeleteUserForm)
        self.cencel_button.clicked.connect(DeleteUserForm.close) # type: ignore
        self.delete_button.clicked.connect(DeleteUserForm.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DeleteUserForm)

    def retranslateUi(self, DeleteUserForm):
        _translate = QtCore.QCoreApplication.translate
        DeleteUserForm.setWindowTitle(_translate("DeleteUserForm", "Dialog"))
        self.delete_button.setText(_translate("DeleteUserForm", "ВИДАЛИТИ!"))
        self.cencel_button.setText(_translate("DeleteUserForm", "Відмінити"))
        self.quastion.setText(_translate("DeleteUserForm", "Впевнені? Введіть \"ВИДАЛИТИ\""))
        self.lineEdit.setWhatsThis(_translate("DeleteUserForm", "<html><head/><body><p><br/></p></body></html>"))
