# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.setEnabled(True)
        LoginWindow.resize(737, 472)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        LoginWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        LoginWindow.setWindowIcon(icon)
        LoginWindow.setStyleSheet("")
        self.background_field = QtWidgets.QLabel(LoginWindow)
        self.background_field.setGeometry(QtCore.QRect(20, 10, 700, 450))
        self.background_field.setStyleSheet("background-color: rgba(255,255,255,255);\n"
"border-bottom-right-radius: 50px;\n"
"border-top-left-radius: 50px;")
        self.background_field.setText("")
        self.background_field.setObjectName("background_field")
        self.baground_company_name_slogan = QtWidgets.QLabel(LoginWindow)
        self.baground_company_name_slogan.setGeometry(QtCore.QRect(20, 90, 350, 120))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.baground_company_name_slogan.setFont(font)
        self.baground_company_name_slogan.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"color: rgb(255, 255, 255);")
        self.baground_company_name_slogan.setText("")
        self.baground_company_name_slogan.setAlignment(QtCore.Qt.AlignCenter)
        self.baground_company_name_slogan.setObjectName("baground_company_name_slogan")
        self.layoutWidget = QtWidgets.QWidget(LoginWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 90, 268, 105))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.company_name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.company_name.setFont(font)
        self.company_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.company_name.setObjectName("company_name")
        self.verticalLayout.addWidget(self.company_name)
        self.company_slogan = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.company_slogan.setFont(font)
        self.company_slogan.setStyleSheet("color: rgb(255, 255, 255);")
        self.company_slogan.setObjectName("company_slogan")
        self.verticalLayout.addWidget(self.company_slogan)
        self.closeButton = QtWidgets.QPushButton(LoginWindow)
        self.closeButton.setGeometry(QtCore.QRect(691, 14, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.closeButton.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"color: rgba(189, 189, 189, 0);")
        self.closeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/close-window-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon1)
        self.closeButton.setIconSize(QtCore.QSize(16, 16))
        self.closeButton.setObjectName("closeButton")
        self.pic = QtWidgets.QLabel(LoginWindow)
        self.pic.setGeometry(QtCore.QRect(20, 10, 350, 450))
        self.pic.setStyleSheet("background-color: rgba(0,0,0,50);\n"
"border-top-left-radius: 50px;")
        self.pic.setText("")
        self.pic.setObjectName("pic")
        self.pic2 = QtWidgets.QLabel(LoginWindow)
        self.pic2.setGeometry(QtCore.QRect(20, 10, 350, 450))
        self.pic2.setStyleSheet("border-image: url(:/images/images/login_image.jpg);\n"
"border-top-left-radius: 50px;")
        self.pic2.setText("")
        self.pic2.setObjectName("pic2")
        self.login_form = QtWidgets.QWidget(LoginWindow)
        self.login_form.setGeometry(QtCore.QRect(380, 110, 330, 340))
        self.login_form.setObjectName("login_form")
        self.login_input = QtWidgets.QLineEdit(self.login_form)
        self.login_input.setGeometry(QtCore.QRect(10, 0, 310, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.login_input.setFont(font)
        self.login_input.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.login_input.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-left: 7px")
        self.login_input.setObjectName("login_input")
        self.password_input = QtWidgets.QLineEdit(self.login_form)
        self.password_input.setGeometry(QtCore.QRect(10, 40, 310, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-left: 7px")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.message_label = QtWidgets.QLabel(self.login_form)
        self.message_label.setGeometry(QtCore.QRect(10, 130, 310, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.message_label.setFont(font)
        self.message_label.setStyleSheet("color: rgb(230, 0, 0);\n"
"font: 12px \"Century Gothic\";\n"
"font-weight: bold;")
        self.message_label.setText("")
        self.message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label.setObjectName("message_label")
        self.enter_button = QtWidgets.QPushButton(self.login_form)
        self.enter_button.setGeometry(QtCore.QRect(10, 240, 300, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.enter_button.setFont(font)
        self.enter_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enter_button.setStyleSheet("QPushButton#enter_button{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(67, 104, 95, 255), stop:1 rgba(255, 203, 158, 255));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 10px;\n"
"}  \n"
"\n"
"QPushButton#enter_button:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(67, 104, 95, 150), stop:1 rgba(255, 203, 158, 150));\n"
"}\n"
"\n"
"QPushButton#enter_button:pressed{\n"
"    font-size: 22px;\n"
"    background-color: rgba(205, 159, 125, 155);\n"
"}")
        self.enter_button.setCheckable(False)
        self.enter_button.setObjectName("enter_button")
        self.forgot_login_password = QtWidgets.QLabel(self.login_form)
        self.forgot_login_password.setGeometry(QtCore.QRect(10, 310, 310, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.forgot_login_password.setFont(font)
        self.forgot_login_password.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgot_login_password.setStyleSheet("color: rgba(0, 0, 0, 210);")
        self.forgot_login_password.setAlignment(QtCore.Qt.AlignCenter)
        self.forgot_login_password.setObjectName("forgot_login_password")
        self.registration_form = QtWidgets.QWidget(LoginWindow)
        self.registration_form.setGeometry(QtCore.QRect(380, 110, 330, 340))
        self.registration_form.setObjectName("registration_form")
        self.password_input_reg_confirm = QtWidgets.QLineEdit(self.registration_form)
        self.password_input_reg_confirm.setGeometry(QtCore.QRect(10, 120, 310, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.password_input_reg_confirm.setFont(font)
        self.password_input_reg_confirm.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-left: 7px")
        self.password_input_reg_confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input_reg_confirm.setObjectName("password_input_reg_confirm")
        self.l_name_input_reg = QtWidgets.QLineEdit(self.registration_form)
        self.l_name_input_reg.setGeometry(QtCore.QRect(160, 0, 160, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.l_name_input_reg.setFont(font)
        self.l_name_input_reg.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.l_name_input_reg.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-left: 7px")
        self.l_name_input_reg.setObjectName("l_name_input_reg")
        self.login_input_reg = QtWidgets.QLineEdit(self.registration_form)
        self.login_input_reg.setGeometry(QtCore.QRect(10, 40, 310, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.login_input_reg.setFont(font)
        self.login_input_reg.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.login_input_reg.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-left: 7px")
        self.login_input_reg.setObjectName("login_input_reg")
        self.password_input_reg = QtWidgets.QLineEdit(self.registration_form)
        self.password_input_reg.setGeometry(QtCore.QRect(10, 80, 310, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.password_input_reg.setFont(font)
        self.password_input_reg.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-left: 7px")
        self.password_input_reg.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input_reg.setObjectName("password_input_reg")
        self.f_name_input_reg = QtWidgets.QLineEdit(self.registration_form)
        self.f_name_input_reg.setGeometry(QtCore.QRect(10, 0, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.f_name_input_reg.setFont(font)
        self.f_name_input_reg.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.f_name_input_reg.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-left: 7px")
        self.f_name_input_reg.setObjectName("f_name_input_reg")
        self.registration_button = QtWidgets.QPushButton(self.registration_form)
        self.registration_button.setGeometry(QtCore.QRect(10, 240, 300, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.registration_button.setFont(font)
        self.registration_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registration_button.setStyleSheet("QPushButton#registration_button{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(67, 104, 95, 255), stop:1 rgba(255, 203, 158, 255));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 10px;\n"
"}  \n"
"\n"
"QPushButton#registration_button:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(67, 104, 95, 150), stop:1 rgba(255, 203, 158, 150));\n"
"}\n"
"\n"
"QPushButton#registration_button:pressed{\n"
"    font-size: 22px;\n"
"    background-color: rgba(205, 159, 125, 155);\n"
"}")
        self.registration_button.setCheckable(False)
        self.registration_button.setObjectName("registration_button")
        self.message_label_reg = QtWidgets.QLabel(self.registration_form)
        self.message_label_reg.setGeometry(QtCore.QRect(10, 210, 310, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.message_label_reg.setFont(font)
        self.message_label_reg.setStyleSheet("color: rgb(230, 0, 0);\n"
"font: 12px \"Century Gothic\";\n"
"font-weight: bold;")
        self.message_label_reg.setText("")
        self.message_label_reg.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label_reg.setObjectName("message_label_reg")
        self.email_input_reg = QtWidgets.QLineEdit(self.registration_form)
        self.email_input_reg.setGeometry(QtCore.QRect(10, 160, 310, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.email_input_reg.setFont(font)
        self.email_input_reg.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-left: 7px")
        self.email_input_reg.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email_input_reg.setObjectName("email_input_reg")
        self.lang = QtWidgets.QWidget(LoginWindow)
        self.lang.setGeometry(QtCore.QRect(370, 10, 50, 22))
        self.lang.setStyleSheet("#lang QRadioButton {\n"
"    font: 10pt \"Century Gothic\";\n"
"    color: rgba(0, 0, 0, 100)\n"
"}\n"
"\n"
"#lang QRadioButton::indicator {\n"
"    background-color: rgb(255, 0, 0);\n"
"    width: 0;\n"
"    height: 0;\n"
"}\n"
"#lang QRadioButton::indicator:checked {\n"
"\n"
"}\n"
"\n"
"#lang QRadioButton:checked {\n"
"  color: rgba(0, 0, 0, 255)\n"
"}\n"
"\n"
"")
        self.lang.setObjectName("lang")
        self.ua_radio_btn = QtWidgets.QRadioButton(self.lang)
        self.ua_radio_btn.setGeometry(QtCore.QRect(22, 0, 31, 25))
        self.ua_radio_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ua_radio_btn.setChecked(True)
        self.ua_radio_btn.setObjectName("ua_radio_btn")
        self.lang_button_group = QtWidgets.QButtonGroup(LoginWindow)
        self.lang_button_group.setObjectName("lang_button_group")
        self.lang_button_group.addButton(self.ua_radio_btn)
        self.en_radio_btn = QtWidgets.QRadioButton(self.lang)
        self.en_radio_btn.setGeometry(QtCore.QRect(0, 0, 31, 25))
        self.en_radio_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.en_radio_btn.setStyleSheet("")
        self.en_radio_btn.setShortcut("")
        self.en_radio_btn.setObjectName("en_radio_btn")
        self.lang_button_group.addButton(self.en_radio_btn)
        self.l = QtWidgets.QLabel(self.lang)
        self.l.setGeometry(QtCore.QRect(21, 5, 5, 13))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.l.setFont(font)
        self.l.setObjectName("l")
        self.widget_lang_reg = QtWidgets.QWidget(LoginWindow)
        self.widget_lang_reg.setGeometry(QtCore.QRect(380, 40, 330, 70))
        self.widget_lang_reg.setStyleSheet("#widget_lang_reg QPushButton {\n"
"    font: 12pt \"Century Gothic\";\n"
"    color: rgb(157, 157, 157);\n"
"    border: 0;\n"
"}\n"
"\n"
"#widget_lang_reg QPushButton:checked {\n"
"    font: 32pt \"Century Gothic\";\n"
"    color: rgba(0, 0, 0, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.widget_lang_reg.setObjectName("widget_lang_reg")
        self.change_on_registration_button = QtWidgets.QPushButton(self.widget_lang_reg)
        self.change_on_registration_button.setGeometry(QtCore.QRect(0, 50, 330, 20))
        self.change_on_registration_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_on_registration_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.change_on_registration_button.setStyleSheet("/*\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 12pt \"Century Gothic\";\n"
"color: rgb(157, 157, 157);\n"
"border: 0;\n"
"*/")
        self.change_on_registration_button.setCheckable(True)
        self.change_on_registration_button.setObjectName("change_on_registration_button")
        self.log_reg_button_group = QtWidgets.QButtonGroup(LoginWindow)
        self.log_reg_button_group.setObjectName("log_reg_button_group")
        self.log_reg_button_group.addButton(self.change_on_registration_button)
        self.change_on_enter_button = QtWidgets.QPushButton(self.widget_lang_reg)
        self.change_on_enter_button.setGeometry(QtCore.QRect(0, 0, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.change_on_enter_button.setFont(font)
        self.change_on_enter_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_on_enter_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.change_on_enter_button.setStyleSheet("/*\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 32pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);\n"
"border: 0;\n"
"*/\n"
"\n"
"#change_on_enter_button {\n"
"padding: 0;\n"
"margin:0;}")
        self.change_on_enter_button.setCheckable(True)
        self.change_on_enter_button.setChecked(True)
        self.change_on_enter_button.setObjectName("change_on_enter_button")
        self.log_reg_button_group.addButton(self.change_on_enter_button)
        self.background_field.raise_()
        self.pic2.raise_()
        self.pic.raise_()
        self.baground_company_name_slogan.raise_()
        self.layoutWidget.raise_()
        self.login_form.raise_()
        self.registration_form.raise_()
        self.closeButton.raise_()
        self.lang.raise_()
        self.widget_lang_reg.raise_()

        self.retranslateUi(LoginWindow)
        self.closeButton.clicked.connect(LoginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)
        LoginWindow.setTabOrder(self.login_input, self.password_input)
        LoginWindow.setTabOrder(self.password_input, self.enter_button)
        LoginWindow.setTabOrder(self.enter_button, self.f_name_input_reg)
        LoginWindow.setTabOrder(self.f_name_input_reg, self.l_name_input_reg)
        LoginWindow.setTabOrder(self.l_name_input_reg, self.login_input_reg)
        LoginWindow.setTabOrder(self.login_input_reg, self.password_input_reg)
        LoginWindow.setTabOrder(self.password_input_reg, self.password_input_reg_confirm)
        LoginWindow.setTabOrder(self.password_input_reg_confirm, self.email_input_reg)
        LoginWindow.setTabOrder(self.email_input_reg, self.registration_button)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Form"))
        self.company_name.setText(_translate("LoginWindow", "Домівка"))
        self.company_slogan.setText(_translate("LoginWindow", "Керуємо будинком з легкістю."))
        self.login_input.setPlaceholderText(_translate("LoginWindow", "Логін користувача"))
        self.password_input.setPlaceholderText(_translate("LoginWindow", "Пароль"))
        self.enter_button.setText(_translate("LoginWindow", "Увійти"))
        self.forgot_login_password.setText(_translate("LoginWindow", "Забули логін чи пароль?"))
        self.password_input_reg_confirm.setPlaceholderText(_translate("LoginWindow", "Підтвердити пароль"))
        self.l_name_input_reg.setPlaceholderText(_translate("LoginWindow", "Прізвище"))
        self.login_input_reg.setPlaceholderText(_translate("LoginWindow", "Логін користувача"))
        self.password_input_reg.setPlaceholderText(_translate("LoginWindow", "Пароль"))
        self.f_name_input_reg.setPlaceholderText(_translate("LoginWindow", "Ім\'я"))
        self.registration_button.setText(_translate("LoginWindow", "Зареєструвати"))
        self.email_input_reg.setToolTip(_translate("LoginWindow", "<html><head/><body><p/></body></html>"))
        self.email_input_reg.setPlaceholderText(_translate("LoginWindow", "Email (не обов\'язково)"))
        self.ua_radio_btn.setText(_translate("LoginWindow", "UA"))
        self.en_radio_btn.setText(_translate("LoginWindow", "EN"))
        self.l.setText(_translate("LoginWindow", "|"))
        self.change_on_registration_button.setText(_translate("LoginWindow", "РЕЄТРАЦІЯ"))
        self.change_on_enter_button.setText(_translate("LoginWindow", "ВХІД"))

